import React from 'react'

// This is the first screen the user sees when they enter the app.
// Users will be able to see a card list of bills with interactive icons that redirect to the descriptive bill page.
// We will have a search and filter function in the home page to sort through bills.
export default function HomeScreen(props){
    return(
        <div id="test">
            This is some text to render
        </div>
    );
}

